// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/it512/loong"
	"github.com/it512/loong/orm/ent/inst"
	"github.com/it512/loong/orm/ent/predicate"
)

// InstUpdate is the builder for updating Inst entities.
type InstUpdate struct {
	config
	hooks    []Hook
	mutation *InstMutation
}

// Where appends a list predicates to the InstUpdate builder.
func (_u *InstUpdate) Where(ps ...predicate.Inst) *InstUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *InstUpdate) SetEndTime(v time.Time) *InstUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *InstUpdate) SetNillableEndTime(v *time.Time) *InstUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *InstUpdate) ClearEndTime() *InstUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetInit sets the "init" field.
func (_u *InstUpdate) SetInit(v loong.Var) *InstUpdate {
	_u.mutation.SetInit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InstUpdate) SetStatus(v int) *InstUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InstUpdate) SetNillableStatus(v *int) *InstUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *InstUpdate) AddStatus(v int) *InstUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *InstUpdate) SetVersion(v int) *InstUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InstUpdate) SetNillableVersion(v *int) *InstUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InstUpdate) AddVersion(v int) *InstUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the InstMutation object of the builder.
func (_u *InstUpdate) Mutation() *InstMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InstUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(inst.Table, inst.Columns, sqlgraph.NewFieldSpec(inst.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(inst.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(inst.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Init(); ok {
		_spec.SetField(inst.FieldInit, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inst.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(inst.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(inst.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(inst.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inst.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstUpdateOne is the builder for updating a single Inst entity.
type InstUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstMutation
}

// SetEndTime sets the "end_time" field.
func (_u *InstUpdateOne) SetEndTime(v time.Time) *InstUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *InstUpdateOne) SetNillableEndTime(v *time.Time) *InstUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *InstUpdateOne) ClearEndTime() *InstUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetInit sets the "init" field.
func (_u *InstUpdateOne) SetInit(v loong.Var) *InstUpdateOne {
	_u.mutation.SetInit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InstUpdateOne) SetStatus(v int) *InstUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InstUpdateOne) SetNillableStatus(v *int) *InstUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *InstUpdateOne) AddStatus(v int) *InstUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *InstUpdateOne) SetVersion(v int) *InstUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InstUpdateOne) SetNillableVersion(v *int) *InstUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InstUpdateOne) AddVersion(v int) *InstUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the InstMutation object of the builder.
func (_u *InstUpdateOne) Mutation() *InstMutation {
	return _u.mutation
}

// Where appends a list predicates to the InstUpdate builder.
func (_u *InstUpdateOne) Where(ps ...predicate.Inst) *InstUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstUpdateOne) Select(field string, fields ...string) *InstUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Inst entity.
func (_u *InstUpdateOne) Save(ctx context.Context) (*Inst, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstUpdateOne) SaveX(ctx context.Context) *Inst {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InstUpdateOne) sqlSave(ctx context.Context) (_node *Inst, err error) {
	_spec := sqlgraph.NewUpdateSpec(inst.Table, inst.Columns, sqlgraph.NewFieldSpec(inst.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Inst.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inst.FieldID)
		for _, f := range fields {
			if !inst.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inst.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(inst.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(inst.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Init(); ok {
		_spec.SetField(inst.FieldInit, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inst.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(inst.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(inst.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(inst.FieldVersion, field.TypeInt, value)
	}
	_node = &Inst{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inst.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
