// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/it512/loong"
	"github.com/it512/loong/orm/ent/inst"
)

// InstCreate is the builder for creating a Inst entity.
type InstCreate struct {
	config
	mutation *InstMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInstID sets the "inst_id" field.
func (_c *InstCreate) SetInstID(v string) *InstCreate {
	_c.mutation.SetInstID(v)
	return _c
}

// SetProcID sets the "proc_id" field.
func (_c *InstCreate) SetProcID(v string) *InstCreate {
	_c.mutation.SetProcID(v)
	return _c
}

// SetBusiKey sets the "busi_key" field.
func (_c *InstCreate) SetBusiKey(v string) *InstCreate {
	_c.mutation.SetBusiKey(v)
	return _c
}

// SetBusiType sets the "busi_type" field.
func (_c *InstCreate) SetBusiType(v string) *InstCreate {
	_c.mutation.SetBusiType(v)
	return _c
}

// SetStarter sets the "starter" field.
func (_c *InstCreate) SetStarter(v string) *InstCreate {
	_c.mutation.SetStarter(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *InstCreate) SetStartTime(v time.Time) *InstCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *InstCreate) SetNillableStartTime(v *time.Time) *InstCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *InstCreate) SetEndTime(v time.Time) *InstCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *InstCreate) SetNillableEndTime(v *time.Time) *InstCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetInit sets the "init" field.
func (_c *InstCreate) SetInit(v loong.Var) *InstCreate {
	_c.mutation.SetInit(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InstCreate) SetStatus(v int) *InstCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InstCreate) SetNillableStatus(v *int) *InstCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *InstCreate) SetVersion(v int) *InstCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *InstCreate) SetNillableVersion(v *int) *InstCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InstCreate) SetID(v uuid.UUID) *InstCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InstCreate) SetNillableID(v *uuid.UUID) *InstCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InstMutation object of the builder.
func (_c *InstCreate) Mutation() *InstMutation {
	return _c.mutation
}

// Save creates the Inst in the database.
func (_c *InstCreate) Save(ctx context.Context) (*Inst, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstCreate) SaveX(ctx context.Context) *Inst {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstCreate) defaults() {
	if _, ok := _c.mutation.StartTime(); !ok {
		v := inst.DefaultStartTime()
		_c.mutation.SetStartTime(v)
	}
	if _, ok := _c.mutation.Init(); !ok {
		v := inst.DefaultInit
		_c.mutation.SetInit(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := inst.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := inst.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := inst.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstCreate) check() error {
	if _, ok := _c.mutation.InstID(); !ok {
		return &ValidationError{Name: "inst_id", err: errors.New(`ent: missing required field "Inst.inst_id"`)}
	}
	if v, ok := _c.mutation.InstID(); ok {
		if err := inst.InstIDValidator(v); err != nil {
			return &ValidationError{Name: "inst_id", err: fmt.Errorf(`ent: validator failed for field "Inst.inst_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProcID(); !ok {
		return &ValidationError{Name: "proc_id", err: errors.New(`ent: missing required field "Inst.proc_id"`)}
	}
	if v, ok := _c.mutation.ProcID(); ok {
		if err := inst.ProcIDValidator(v); err != nil {
			return &ValidationError{Name: "proc_id", err: fmt.Errorf(`ent: validator failed for field "Inst.proc_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BusiKey(); !ok {
		return &ValidationError{Name: "busi_key", err: errors.New(`ent: missing required field "Inst.busi_key"`)}
	}
	if v, ok := _c.mutation.BusiKey(); ok {
		if err := inst.BusiKeyValidator(v); err != nil {
			return &ValidationError{Name: "busi_key", err: fmt.Errorf(`ent: validator failed for field "Inst.busi_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BusiType(); !ok {
		return &ValidationError{Name: "busi_type", err: errors.New(`ent: missing required field "Inst.busi_type"`)}
	}
	if v, ok := _c.mutation.BusiType(); ok {
		if err := inst.BusiTypeValidator(v); err != nil {
			return &ValidationError{Name: "busi_type", err: fmt.Errorf(`ent: validator failed for field "Inst.busi_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Starter(); !ok {
		return &ValidationError{Name: "starter", err: errors.New(`ent: missing required field "Inst.starter"`)}
	}
	if v, ok := _c.mutation.Starter(); ok {
		if err := inst.StarterValidator(v); err != nil {
			return &ValidationError{Name: "starter", err: fmt.Errorf(`ent: validator failed for field "Inst.starter": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Inst.start_time"`)}
	}
	if _, ok := _c.mutation.Init(); !ok {
		return &ValidationError{Name: "init", err: errors.New(`ent: missing required field "Inst.init"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Inst.status"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Inst.version"`)}
	}
	return nil
}

func (_c *InstCreate) sqlSave(ctx context.Context) (*Inst, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstCreate) createSpec() (*Inst, *sqlgraph.CreateSpec) {
	var (
		_node = &Inst{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inst.Table, sqlgraph.NewFieldSpec(inst.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.InstID(); ok {
		_spec.SetField(inst.FieldInstID, field.TypeString, value)
		_node.InstID = value
	}
	if value, ok := _c.mutation.ProcID(); ok {
		_spec.SetField(inst.FieldProcID, field.TypeString, value)
		_node.ProcID = value
	}
	if value, ok := _c.mutation.BusiKey(); ok {
		_spec.SetField(inst.FieldBusiKey, field.TypeString, value)
		_node.BusiKey = value
	}
	if value, ok := _c.mutation.BusiType(); ok {
		_spec.SetField(inst.FieldBusiType, field.TypeString, value)
		_node.BusiType = value
	}
	if value, ok := _c.mutation.Starter(); ok {
		_spec.SetField(inst.FieldStarter, field.TypeString, value)
		_node.Starter = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(inst.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(inst.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.Init(); ok {
		_spec.SetField(inst.FieldInit, field.TypeJSON, value)
		_node.Init = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(inst.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(inst.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inst.Create().
//		SetInstID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstUpsert) {
//			SetInstID(v+v).
//		}).
//		Exec(ctx)
func (_c *InstCreate) OnConflict(opts ...sql.ConflictOption) *InstUpsertOne {
	_c.conflict = opts
	return &InstUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inst.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstCreate) OnConflictColumns(columns ...string) *InstUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstUpsertOne{
		create: _c,
	}
}

type (
	// InstUpsertOne is the builder for "upsert"-ing
	//  one Inst node.
	InstUpsertOne struct {
		create *InstCreate
	}

	// InstUpsert is the "OnConflict" setter.
	InstUpsert struct {
		*sql.UpdateSet
	}
)

// SetEndTime sets the "end_time" field.
func (u *InstUpsert) SetEndTime(v time.Time) *InstUpsert {
	u.Set(inst.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *InstUpsert) UpdateEndTime() *InstUpsert {
	u.SetExcluded(inst.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "end_time" field.
func (u *InstUpsert) ClearEndTime() *InstUpsert {
	u.SetNull(inst.FieldEndTime)
	return u
}

// SetInit sets the "init" field.
func (u *InstUpsert) SetInit(v loong.Var) *InstUpsert {
	u.Set(inst.FieldInit, v)
	return u
}

// UpdateInit sets the "init" field to the value that was provided on create.
func (u *InstUpsert) UpdateInit() *InstUpsert {
	u.SetExcluded(inst.FieldInit)
	return u
}

// SetStatus sets the "status" field.
func (u *InstUpsert) SetStatus(v int) *InstUpsert {
	u.Set(inst.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InstUpsert) UpdateStatus() *InstUpsert {
	u.SetExcluded(inst.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *InstUpsert) AddStatus(v int) *InstUpsert {
	u.Add(inst.FieldStatus, v)
	return u
}

// SetVersion sets the "version" field.
func (u *InstUpsert) SetVersion(v int) *InstUpsert {
	u.Set(inst.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *InstUpsert) UpdateVersion() *InstUpsert {
	u.SetExcluded(inst.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *InstUpsert) AddVersion(v int) *InstUpsert {
	u.Add(inst.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Inst.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inst.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstUpsertOne) UpdateNewValues() *InstUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inst.FieldID)
		}
		if _, exists := u.create.mutation.InstID(); exists {
			s.SetIgnore(inst.FieldInstID)
		}
		if _, exists := u.create.mutation.ProcID(); exists {
			s.SetIgnore(inst.FieldProcID)
		}
		if _, exists := u.create.mutation.BusiKey(); exists {
			s.SetIgnore(inst.FieldBusiKey)
		}
		if _, exists := u.create.mutation.BusiType(); exists {
			s.SetIgnore(inst.FieldBusiType)
		}
		if _, exists := u.create.mutation.Starter(); exists {
			s.SetIgnore(inst.FieldStarter)
		}
		if _, exists := u.create.mutation.StartTime(); exists {
			s.SetIgnore(inst.FieldStartTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inst.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InstUpsertOne) Ignore() *InstUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstUpsertOne) DoNothing() *InstUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstCreate.OnConflict
// documentation for more info.
func (u *InstUpsertOne) Update(set func(*InstUpsert)) *InstUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstUpsert{UpdateSet: update})
	}))
	return u
}

// SetEndTime sets the "end_time" field.
func (u *InstUpsertOne) SetEndTime(v time.Time) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *InstUpsertOne) UpdateEndTime() *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *InstUpsertOne) ClearEndTime() *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.ClearEndTime()
	})
}

// SetInit sets the "init" field.
func (u *InstUpsertOne) SetInit(v loong.Var) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.SetInit(v)
	})
}

// UpdateInit sets the "init" field to the value that was provided on create.
func (u *InstUpsertOne) UpdateInit() *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.UpdateInit()
	})
}

// SetStatus sets the "status" field.
func (u *InstUpsertOne) SetStatus(v int) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *InstUpsertOne) AddStatus(v int) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InstUpsertOne) UpdateStatus() *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *InstUpsertOne) SetVersion(v int) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *InstUpsertOne) AddVersion(v int) *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *InstUpsertOne) UpdateVersion() *InstUpsertOne {
	return u.Update(func(s *InstUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *InstUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InstUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InstUpsertOne.ID is not supported by MySQL driver. Use InstUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InstUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InstCreateBulk is the builder for creating many Inst entities in bulk.
type InstCreateBulk struct {
	config
	err      error
	builders []*InstCreate
	conflict []sql.ConflictOption
}

// Save creates the Inst entities in the database.
func (_c *InstCreateBulk) Save(ctx context.Context) ([]*Inst, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inst, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstCreateBulk) SaveX(ctx context.Context) []*Inst {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inst.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstUpsert) {
//			SetInstID(v+v).
//		}).
//		Exec(ctx)
func (_c *InstCreateBulk) OnConflict(opts ...sql.ConflictOption) *InstUpsertBulk {
	_c.conflict = opts
	return &InstUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inst.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstCreateBulk) OnConflictColumns(columns ...string) *InstUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstUpsertBulk{
		create: _c,
	}
}

// InstUpsertBulk is the builder for "upsert"-ing
// a bulk of Inst nodes.
type InstUpsertBulk struct {
	create *InstCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Inst.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inst.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstUpsertBulk) UpdateNewValues() *InstUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inst.FieldID)
			}
			if _, exists := b.mutation.InstID(); exists {
				s.SetIgnore(inst.FieldInstID)
			}
			if _, exists := b.mutation.ProcID(); exists {
				s.SetIgnore(inst.FieldProcID)
			}
			if _, exists := b.mutation.BusiKey(); exists {
				s.SetIgnore(inst.FieldBusiKey)
			}
			if _, exists := b.mutation.BusiType(); exists {
				s.SetIgnore(inst.FieldBusiType)
			}
			if _, exists := b.mutation.Starter(); exists {
				s.SetIgnore(inst.FieldStarter)
			}
			if _, exists := b.mutation.StartTime(); exists {
				s.SetIgnore(inst.FieldStartTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inst.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InstUpsertBulk) Ignore() *InstUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstUpsertBulk) DoNothing() *InstUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstCreateBulk.OnConflict
// documentation for more info.
func (u *InstUpsertBulk) Update(set func(*InstUpsert)) *InstUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstUpsert{UpdateSet: update})
	}))
	return u
}

// SetEndTime sets the "end_time" field.
func (u *InstUpsertBulk) SetEndTime(v time.Time) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *InstUpsertBulk) UpdateEndTime() *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *InstUpsertBulk) ClearEndTime() *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.ClearEndTime()
	})
}

// SetInit sets the "init" field.
func (u *InstUpsertBulk) SetInit(v loong.Var) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.SetInit(v)
	})
}

// UpdateInit sets the "init" field to the value that was provided on create.
func (u *InstUpsertBulk) UpdateInit() *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.UpdateInit()
	})
}

// SetStatus sets the "status" field.
func (u *InstUpsertBulk) SetStatus(v int) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *InstUpsertBulk) AddStatus(v int) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InstUpsertBulk) UpdateStatus() *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *InstUpsertBulk) SetVersion(v int) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *InstUpsertBulk) AddVersion(v int) *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *InstUpsertBulk) UpdateVersion() *InstUpsertBulk {
	return u.Update(func(s *InstUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *InstUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InstCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
