// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/it512/loong"
	"github.com/it512/loong/orm/ent/predicate"
	"github.com/it512/loong/orm/ent/usertask"
)

// UserTaskUpdate is the builder for updating UserTask entities.
type UserTaskUpdate struct {
	config
	hooks    []Hook
	mutation *UserTaskMutation
}

// Where appends a list predicates to the UserTaskUpdate builder.
func (_u *UserTaskUpdate) Where(ps ...predicate.UserTask) *UserTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *UserTaskUpdate) SetOwner(v string) *UserTaskUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *UserTaskUpdate) SetNillableOwner(v *string) *UserTaskUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *UserTaskUpdate) ClearOwner() *UserTaskUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *UserTaskUpdate) SetOperator(v string) *UserTaskUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *UserTaskUpdate) SetNillableOperator(v *string) *UserTaskUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *UserTaskUpdate) ClearOperator() *UserTaskUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// SetInput sets the "input" field.
func (_u *UserTaskUpdate) SetInput(v loong.Var) *UserTaskUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *UserTaskUpdate) SetEndTime(v time.Time) *UserTaskUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *UserTaskUpdate) SetNillableEndTime(v *time.Time) *UserTaskUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *UserTaskUpdate) ClearEndTime() *UserTaskUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserTaskUpdate) SetStatus(v int) *UserTaskUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserTaskUpdate) SetNillableStatus(v *int) *UserTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *UserTaskUpdate) AddStatus(v int) *UserTaskUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserTaskUpdate) SetVersion(v int) *UserTaskUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserTaskUpdate) SetNillableVersion(v *int) *UserTaskUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserTaskUpdate) AddVersion(v int) *UserTaskUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserTaskMutation object of the builder.
func (_u *UserTaskUpdate) Mutation() *UserTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTaskUpdate) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := usertask.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "UserTask.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := usertask.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "UserTask.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *UserTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertask.Table, usertask.Columns, sqlgraph.NewFieldSpec(usertask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ExecIDCleared() {
		_spec.ClearField(usertask.FieldExecID, field.TypeString)
	}
	if _u.mutation.FormKeyCleared() {
		_spec.ClearField(usertask.FieldFormKey, field.TypeString)
	}
	if _u.mutation.ActNameCleared() {
		_spec.ClearField(usertask.FieldActName, field.TypeString)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(usertask.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(usertask.FieldOwner, field.TypeString)
	}
	if _u.mutation.AssigneeCleared() {
		_spec.ClearField(usertask.FieldAssignee, field.TypeString)
	}
	if _u.mutation.CandidateUsersCleared() {
		_spec.ClearField(usertask.FieldCandidateUsers, field.TypeString)
	}
	if _u.mutation.CandidateGroupsCleared() {
		_spec.ClearField(usertask.FieldCandidateGroups, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(usertask.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(usertask.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(usertask.FieldInput, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(usertask.FieldResult, field.TypeInt)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(usertask.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(usertask.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usertask.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(usertask.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(usertask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(usertask.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTaskUpdateOne is the builder for updating a single UserTask entity.
type UserTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTaskMutation
}

// SetOwner sets the "owner" field.
func (_u *UserTaskUpdateOne) SetOwner(v string) *UserTaskUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *UserTaskUpdateOne) SetNillableOwner(v *string) *UserTaskUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *UserTaskUpdateOne) ClearOwner() *UserTaskUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *UserTaskUpdateOne) SetOperator(v string) *UserTaskUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *UserTaskUpdateOne) SetNillableOperator(v *string) *UserTaskUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *UserTaskUpdateOne) ClearOperator() *UserTaskUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// SetInput sets the "input" field.
func (_u *UserTaskUpdateOne) SetInput(v loong.Var) *UserTaskUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *UserTaskUpdateOne) SetEndTime(v time.Time) *UserTaskUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *UserTaskUpdateOne) SetNillableEndTime(v *time.Time) *UserTaskUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *UserTaskUpdateOne) ClearEndTime() *UserTaskUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserTaskUpdateOne) SetStatus(v int) *UserTaskUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserTaskUpdateOne) SetNillableStatus(v *int) *UserTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *UserTaskUpdateOne) AddStatus(v int) *UserTaskUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserTaskUpdateOne) SetVersion(v int) *UserTaskUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserTaskUpdateOne) SetNillableVersion(v *int) *UserTaskUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserTaskUpdateOne) AddVersion(v int) *UserTaskUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserTaskMutation object of the builder.
func (_u *UserTaskUpdateOne) Mutation() *UserTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserTaskUpdate builder.
func (_u *UserTaskUpdateOne) Where(ps ...predicate.UserTask) *UserTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTaskUpdateOne) Select(field string, fields ...string) *UserTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTask entity.
func (_u *UserTaskUpdateOne) Save(ctx context.Context) (*UserTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTaskUpdateOne) SaveX(ctx context.Context) *UserTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := usertask.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "UserTask.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := usertask.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "UserTask.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *UserTaskUpdateOne) sqlSave(ctx context.Context) (_node *UserTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertask.Table, usertask.Columns, sqlgraph.NewFieldSpec(usertask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertask.FieldID)
		for _, f := range fields {
			if !usertask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ExecIDCleared() {
		_spec.ClearField(usertask.FieldExecID, field.TypeString)
	}
	if _u.mutation.FormKeyCleared() {
		_spec.ClearField(usertask.FieldFormKey, field.TypeString)
	}
	if _u.mutation.ActNameCleared() {
		_spec.ClearField(usertask.FieldActName, field.TypeString)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(usertask.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(usertask.FieldOwner, field.TypeString)
	}
	if _u.mutation.AssigneeCleared() {
		_spec.ClearField(usertask.FieldAssignee, field.TypeString)
	}
	if _u.mutation.CandidateUsersCleared() {
		_spec.ClearField(usertask.FieldCandidateUsers, field.TypeString)
	}
	if _u.mutation.CandidateGroupsCleared() {
		_spec.ClearField(usertask.FieldCandidateGroups, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(usertask.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(usertask.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(usertask.FieldInput, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(usertask.FieldResult, field.TypeInt)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(usertask.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(usertask.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usertask.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(usertask.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(usertask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(usertask.FieldVersion, field.TypeInt, value)
	}
	_node = &UserTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
