package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"

	"github.com/it512/loong"
	"github.com/it512/loong/web/gql/graph/model"
)

// StartProc is the resolver for the startProc field.
func (r *mutationResolver) StartProc(ctx context.Context, input loong.StartProcCmd) (*model.ProcReturn, error) {
	instID, err := r.Engine.StartProc(ctx, input)
	return &model.ProcReturn{InstID: instID}, err
}

// CommitTask is the resolver for the commitTask field.
func (r *mutationResolver) CommitTask(ctx context.Context, input loong.UserTaskCommitCmd) (*model.CommitTaskReturn, error) {
	err := r.Engine.CommitTask(ctx, input)
	return &model.CommitTaskReturn{TaskID: input.TaskID}, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
