package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"

	"github.com/it512/loong/todo"
)

// TodosPage is the resolver for the todosPage field.
func (r *queryResolver) TodosPage(ctx context.Context, input todo.TodoQueryParam) (*todo.TodoPageResult, error) {
	return r.Todo.QueryTaskPage(ctx, input)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
