// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/it512/loong/hg/internal/ent/hg"
	"github.com/it512/loong/hg/internal/ent/predicate"
)

// HgUpdate is the builder for updating Hg entities.
type HgUpdate struct {
	config
	hooks    []Hook
	mutation *HgMutation
}

// Where appends a list predicates to the HgUpdate builder.
func (hu *HgUpdate) Where(ps ...predicate.Hg) *HgUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetStatus sets the "status" field.
func (hu *HgUpdate) SetStatus(i int) *HgUpdate {
	hu.mutation.ResetStatus()
	hu.mutation.SetStatus(i)
	return hu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (hu *HgUpdate) SetNillableStatus(i *int) *HgUpdate {
	if i != nil {
		hu.SetStatus(*i)
	}
	return hu
}

// AddStatus adds i to the "status" field.
func (hu *HgUpdate) AddStatus(i int) *HgUpdate {
	hu.mutation.AddStatus(i)
	return hu
}

// Mutation returns the HgMutation object of the builder.
func (hu *HgUpdate) Mutation() *HgMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HgUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HgUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HgUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HgUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HgUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hg.Table, hg.Columns, sqlgraph.NewFieldSpec(hg.FieldID, field.TypeUUID))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Status(); ok {
		_spec.SetField(hg.FieldStatus, field.TypeInt, value)
	}
	if value, ok := hu.mutation.AddedStatus(); ok {
		_spec.AddField(hg.FieldStatus, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hg.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HgUpdateOne is the builder for updating a single Hg entity.
type HgUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HgMutation
}

// SetStatus sets the "status" field.
func (huo *HgUpdateOne) SetStatus(i int) *HgUpdateOne {
	huo.mutation.ResetStatus()
	huo.mutation.SetStatus(i)
	return huo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (huo *HgUpdateOne) SetNillableStatus(i *int) *HgUpdateOne {
	if i != nil {
		huo.SetStatus(*i)
	}
	return huo
}

// AddStatus adds i to the "status" field.
func (huo *HgUpdateOne) AddStatus(i int) *HgUpdateOne {
	huo.mutation.AddStatus(i)
	return huo
}

// Mutation returns the HgMutation object of the builder.
func (huo *HgUpdateOne) Mutation() *HgMutation {
	return huo.mutation
}

// Where appends a list predicates to the HgUpdate builder.
func (huo *HgUpdateOne) Where(ps ...predicate.Hg) *HgUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HgUpdateOne) Select(field string, fields ...string) *HgUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hg entity.
func (huo *HgUpdateOne) Save(ctx context.Context) (*Hg, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HgUpdateOne) SaveX(ctx context.Context) *Hg {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HgUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HgUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HgUpdateOne) sqlSave(ctx context.Context) (_node *Hg, err error) {
	_spec := sqlgraph.NewUpdateSpec(hg.Table, hg.Columns, sqlgraph.NewFieldSpec(hg.FieldID, field.TypeUUID))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hg.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hg.FieldID)
		for _, f := range fields {
			if !hg.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hg.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Status(); ok {
		_spec.SetField(hg.FieldStatus, field.TypeInt, value)
	}
	if value, ok := huo.mutation.AddedStatus(); ok {
		_spec.AddField(hg.FieldStatus, field.TypeInt, value)
	}
	_node = &Hg{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hg.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
