// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Inst is the predicate function for inst builders.
type Inst func(*sql.Selector)

// UserTask is the predicate function for usertask builders.
type UserTask func(*sql.Selector)
