// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IDHgColumns holds the columns for the "id_hg" table.
	IDHgColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "human_code", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "human_name", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "group_code", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "group_name", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "status", Type: field.TypeInt, Default: 0},
	}
	// IDHgTable holds the schema information for the "id_hg" table.
	IDHgTable = &schema.Table{
		Name:       "id_hg",
		Columns:    IDHgColumns,
		PrimaryKey: []*schema.Column{IDHgColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hg_human_code",
				Unique:  false,
				Columns: []*schema.Column{IDHgColumns[1]},
			},
			{
				Name:    "hg_group_code",
				Unique:  false,
				Columns: []*schema.Column{IDHgColumns[3]},
			},
			{
				Name:    "hg_status",
				Unique:  false,
				Columns: []*schema.Column{IDHgColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IDHgTable,
	}
)

func init() {
	IDHgTable.Annotation = &entsql.Annotation{
		Table: "id_hg",
	}
}
