// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommitTaskReturn struct {
	TaskID string `json:"task_id"`
}

type Mutation struct {
}

type ProcReturn struct {
	InstID string `json:"inst_id"`
}

type Query struct {
}
